// This file is autogenerated by scripts/build-rule-schemas.js
// Do NOT modify this file manually

import type { Linter } from 'eslint';

export interface ImportXRules {
  'import-x/no-unresolved': Linter.RuleEntry;
  'import-x/named': Linter.RuleEntry;
  'import-x/default': Linter.RuleEntry;
  'import-x/namespace': Linter.RuleEntry;
  'import-x/no-namespace': Linter.RuleEntry;
  'import-x/export': Linter.RuleEntry;
  'import-x/no-mutable-exports': Linter.RuleEntry;
  'import-x/extensions': Linter.RuleEntry;
  'import-x/no-restricted-paths': Linter.RuleEntry;
  'import-x/no-internal-modules': Linter.RuleEntry;
  'import-x/group-exports': Linter.RuleEntry;
  'import-x/no-relative-packages': Linter.RuleEntry;
  'import-x/no-relative-parent-imports': Linter.RuleEntry;
  'import-x/consistent-type-specifier-style': Linter.RuleEntry;
  'import-x/no-self-import': Linter.RuleEntry;
  'import-x/no-cycle': Linter.RuleEntry;
  'import-x/no-named-default': Linter.RuleEntry;
  'import-x/no-named-as-default': Linter.RuleEntry;
  'import-x/no-named-as-default-member': Linter.RuleEntry;
  'import-x/no-anonymous-default-export': Linter.RuleEntry;
  'import-x/no-rename-default': Linter.RuleEntry;
  'import-x/no-unused-modules': Linter.RuleEntry;
  'import-x/no-commonjs': Linter.RuleEntry;
  'import-x/no-amd': Linter.RuleEntry;
  'import-x/no-duplicates': Linter.RuleEntry;
  'import-x/first': Linter.RuleEntry;
  'import-x/max-dependencies': Linter.RuleEntry;
  'import-x/no-extraneous-dependencies': Linter.RuleEntry;
  'import-x/no-absolute-path': Linter.RuleEntry;
  'import-x/no-nodejs-modules': Linter.RuleEntry;
  'import-x/no-webpack-loader-syntax': Linter.RuleEntry;
  'import-x/order': Linter.RuleEntry;
  'import-x/newline-after-import': Linter.RuleEntry;
  'import-x/prefer-default-export': Linter.RuleEntry;
  'import-x/no-default-export': Linter.RuleEntry;
  'import-x/no-named-export': Linter.RuleEntry;
  'import-x/no-dynamic-require': Linter.RuleEntry;
  'import-x/unambiguous': Linter.RuleEntry;
  'import-x/no-unassigned-import': Linter.RuleEntry;
  'import-x/no-useless-path-segments': Linter.RuleEntry;
  'import-x/dynamic-import-chunkname': Linter.RuleEntry;
  'import-x/no-import-module-exports': Linter.RuleEntry;
  'import-x/no-empty-named-blocks': Linter.RuleEntry;
  'import-x/exports-last': Linter.RuleEntry;
  'import-x/no-deprecated': Linter.RuleEntry;
  'import-x/imports-first': Linter.RuleEntry;
}