// This file is autogenerated by scripts/build-rule-schemas.js
// Do NOT modify this file manually

import type { Linter } from 'eslint';

export interface PackageJsonRules {
  'package-json/no-empty-fields': Linter.RuleEntry;
  'package-json/no-redundant-files': Linter.RuleEntry;
  'package-json/order-properties': Linter.RuleEntry;
  'package-json/require-author': Linter.RuleEntry;
  'package-json/require-description': Linter.RuleEntry;
  'package-json/require-engines': Linter.RuleEntry;
  'package-json/require-files': Linter.RuleEntry;
  'package-json/require-keywords': Linter.RuleEntry;
  'package-json/require-name': Linter.RuleEntry;
  'package-json/require-types': Linter.RuleEntry;
  'package-json/require-version': Linter.RuleEntry;
  'package-json/repository-shorthand': Linter.RuleEntry;
  'package-json/restrict-dependency-ranges': Linter.RuleEntry;
  'package-json/sort-collections': Linter.RuleEntry;
  'package-json/unique-dependencies': Linter.RuleEntry;
  'package-json/valid-local-dependency': Linter.RuleEntry;
  'package-json/valid-name': Linter.RuleEntry;
  'package-json/valid-package-definition': Linter.RuleEntry;
  'package-json/valid-repository-directory': Linter.RuleEntry;
  'package-json/valid-version': Linter.RuleEntry;
  'package-json/valid-package-def': Linter.RuleEntry;
}