// This file is autogenerated by scripts/build-rule-schemas.js
// Do NOT modify this file manually

import type { Linter } from 'eslint';

export interface PerfectionistRules {
  'perfectionist/sort-variable-declarations': Linter.RuleEntry;
  'perfectionist/sort-intersection-types': Linter.RuleEntry;
  'perfectionist/sort-heritage-clauses': Linter.RuleEntry;
  'perfectionist/sort-array-includes': Linter.RuleEntry;
  'perfectionist/sort-named-imports': Linter.RuleEntry;
  'perfectionist/sort-named-exports': Linter.RuleEntry;
  'perfectionist/sort-object-types': Linter.RuleEntry;
  'perfectionist/sort-union-types': Linter.RuleEntry;
  'perfectionist/sort-switch-case': Linter.RuleEntry;
  'perfectionist/sort-decorators': Linter.RuleEntry;
  'perfectionist/sort-interfaces': Linter.RuleEntry;
  'perfectionist/sort-jsx-props': Linter.RuleEntry;
  'perfectionist/sort-modules': Linter.RuleEntry;
  'perfectionist/sort-classes': Linter.RuleEntry;
  'perfectionist/sort-imports': Linter.RuleEntry;
  'perfectionist/sort-exports': Linter.RuleEntry;
  'perfectionist/sort-objects': Linter.RuleEntry;
  'perfectionist/sort-enums': Linter.RuleEntry;
  'perfectionist/sort-sets': Linter.RuleEntry;
  'perfectionist/sort-maps': Linter.RuleEntry;
}